### ISSUE TITLE
WKS are always =1

### ISSUE THREAD

**Issue by Dolphin4mi** [DominikPenk/mesh-signatures#3]
after changing the 106 line 
        phi2       = np.square(self.evecs[:, 1:])
to 
        phi2       = np.square(self.evecs[:, 0:])
I'm not sure it is correct, but the WKS are always =1

**Comment by DominikPenk** [comment]
Hey,
That seems to be a nagging problem. 
This project was the implementation of some related work during my PhD. Since then, I have moved on from the field of mesh processing. Unfortunately, my lizard brain has decided to mostly forget both the details of this implementation and the theory behind it. Right now, I won't commit my time to reading the referenced papers or diving into the codebase to fix the issue.

But if you decide to fix the bug, feel free to send a pull request.
